services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  django-api:
    build:
      context: .
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - redis
      - db
    volumes:
      - .:/app
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000" ]
    env_file:
      - .env 

  celery-worker:
    build:
      context: .
    restart: always
    depends_on:
      - db
      - redis
      - django-api
    env_file:
      - .env 
    volumes:
      - .:/app
    command: ["celery", "-A", "config", "worker", "--loglevel=info"]
