# Generated by Django 5.2.1 on 2025-08-13 14:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='processing', max_length=20)),
                ('input_content', models.TextField(blank=True, null=True)),
                ('target_keyword', models.CharField(max_length=255)),
                ('optimized_imporvements', models.JSONField(blank=True, null=True)),
                ('optimized_content', models.TextField(blank=True, null=True)),
                ('processing_time', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('input_url', models.URLField(blank=True, null=True)),
                ('seo_score', models.FloatField(blank=True, null=True)),
                ('word_count', models.IntegerField(blank=True, null=True)),
                ('keyword_density', models.FloatField(blank=True, null=True)),
                ('avg_sentence_length', models.FloatField(blank=True, null=True)),
                ('readability_score', models.FloatField(blank=True, null=True)),
                ('issues', models.JSONField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OptimizationRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='processing', max_length=20)),
                ('target_keyword', models.CharField(max_length=255)),
                ('optimized_imporvements', models.JSONField(blank=True, null=True)),
                ('optimized_content', models.TextField(blank=True, null=True)),
                ('processing_time', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('input_content', models.TextField()),
                ('target_length', models.IntegerField()),
                ('tone', models.CharField(max_length=255)),
                ('optimized_keyword_denisty', models.FloatField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
